[tool.poetry]
name = "clean-markdown"
version = "0.1.0"
description = ""
authors = ["bahamondex <oscar.bahamonde@oscarbahamonde.awsapps.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
